[project]
name = "py-plants-vs-zombies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Rösch", email = "droesch91@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
py-plants-vs-zombies = "py_plants_vs_zombies:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
